# Generated by Django 6.0.3 on 2026-03-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Placa')),
                ('identificacion', models.BigIntegerField(max_length=20, null=True, verbose_name='Identificación')),
                ('nombres', models.CharField(max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, null=True, verbose_name='Apellidos')),
                ('telefono', models.BigIntegerField(max_length=10, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Correo')),
                ('diagnostico', models.TextField(null=True, verbose_name='Diagnóstico')),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha de Ingreso')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
