# Generated by Django 6.0.3 on 2026-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_cliente_identificacion_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='diagnostico',
            field=models.TextField(null=True, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.BigIntegerField(null=True, verbose_name='Numero de Identificacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen del Vehiculo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='placa',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Placa del Vehiculo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(null=True, verbose_name='Numero de Telefono'),
        ),
    ]
