# Generated by Django 6.0.3 on 2026-06-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_vehiculo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='Correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ID',
            field=models.BigIntegerField(null=True, verbose_name='Numero de Identificacion'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='diagnostico',
            field=models.TextField(null=True, verbose_name='Diagnostico'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ingreso',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen del Vehiculo'),
        ),
    ]
