# Generated by Django 6.0.3 on 2026-06-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_vehiculo_correo_vehiculo_id_vehiculo_diagnostico_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='Correo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='imagen',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
