# Generated by Django 6.0.3 on 2026-06-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_delete_cliente_remove_vehiculo_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='ID',
            field=models.BigIntegerField(null=True),
        ),
    ]
