# Generated by Django 6.0.3 on 2026-06-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_vehiculo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='Correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='diagnostico',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
