# Generated by Django 6.0.3 on 2026-06-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=15),
        ),
    ]
