# Generated by Django 6.0.3 on 2026-06-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0012_tarea_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
