# Generated by Django 6.0.3 on 2026-06-12 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0015_alter_vehiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900, message='El año deber ser mayor a 1900'), django.core.validators.MaxValueValidator(2026, message='el año ingresado aun no exite')], verbose_name='Año'),
        ),
    ]
