# Generated by Django 6.0.3 on 2026-06-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0017_alter_vehiculo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
