# Generated by Django 6.0.3 on 2026-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0018_vehiculo_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='telefono',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
