# Generated by Django 6.0.3 on 2026-06-12 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0019_alter_vehiculo_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='telefono',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Solo se permiten hasta 10 números y sin caracteres especiales.')]),
        ),
    ]
