# Generated by Django 6.0.3 on 2026-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0021_vehiculoeliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
