# Generated by Django 6.0.3 on 2026-06-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0022_tarea_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='imagen',
        ),
    ]
