# Generated by Django 6.0.3 on 2026-06-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0024_tareaeliminada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tareas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='taller.tarea')),
            ],
        ),
    ]
