# Generated by Django 6.0.3 on 2026-06-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0025_imagentarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
