# Generated by Django 6.0.3 on 2026-06-14 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0027_alter_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='observaciones_finalizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TareaFinalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('tecnico', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_finalizacion', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taller.tarea')),
            ],
        ),
    ]
