# Generated by Django 6.0.3 on 2026-06-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0028_tarea_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareafinalizada',
            name='tarea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalizacion', to='taller.tarea'),
        ),
    ]
