# Generated by Django 6.0.3 on 2026-06-15 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0030_vehiculoentregado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('nombre_recibe', models.CharField(max_length=100)),
                ('identificacion_recibe', models.CharField(max_length=20)),
                ('celular_recibe', models.CharField(max_length=15)),
                ('estado_pago', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente de pago')], max_length=20)),
                ('imagen_entrega', models.ImageField(upload_to='entregas/')),
                ('firma_recibe', models.ImageField(upload_to='firmas/')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='taller.vehiculo')),
            ],
        ),
        migrations.DeleteModel(
            name='VehiculoEntregado',
        ),
    ]
