# Generated by Django 6.0.3 on 2026-06-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0031_entregavehiculo_delete_vehiculoentregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregavehiculo',
            name='firma_recibe',
            field=models.TextField(),
        ),
    ]
