# Generated by Django 6.0.3 on 2026-06-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0032_alter_entregavehiculo_firma_recibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregavehiculo',
            name='firma_recibe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
