# Generated by Django 6.0.3 on 2026-06-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0033_alter_entregavehiculo_firma_recibe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TareaFinalizada',
        ),
    ]
